name: Build and Push from dev to staging and from staging to main

on:
  push:
    branches:
      - dev
      - staging
permissions:
  contents: write

jobs:
  build_and_push_dev_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start and stop Python script
        run: |
          python main.py &               
          sleep 5s                      
          pkill -f "python main.py"      

      - name: Run Tests
        run: | 
          python test.py
          
      - name: Push Dev to staging
        run: |
          git config user.email "artitambe2602@gmail.com"
          git config user.name "Arti Tambe"
          git fetch origin 
          git checkout staging
          git merge --allow-unrelated-histories dev
          git push origin staging

  raise_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start and stop Python script
        run: |
          python main.py &               
          sleep 5s                      
          pkill -f "python main.py"      

      - name: Run Tests
        run: | 
          python test.py

      - name: Create Pull Request
        run: |
          git config user.email "artitambe2602@gmail.com"
          git config user.name "Arti Tambe"
          # Create a pull request from the 'staging' branch to 'main'
          gh pr create --base main --head staging --title "Merge staging into main" --body "Automated pull request."

