name: Build and Push from dev to staging and from staging to main

on:
  push:
    branches:
      - dev
      - staging
permissions:
  contents: write

jobs:
  build_and_push_dev_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify your desired Python version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start and stop Python script
        run: |
          python main.py &               # Start the Python script in the background
          sleep 5s                      # Wait for 5 seconds (adjust the duration as needed)
          pkill -f "python main.py"      # Stop the Python script

      - name: Run Tests
        run: | 
          python test.py
          
      - name: Push Dev to staging
        run: |
          # Configure Git
          git config user.email "artitambe2602@gmail.com"
          git config user.name "Arti Tambe"

          #Fetch Remote Branches test branches
          git fetch origin 

          #Checkout Staging Branch
          git checkout staging

          # Merge Dev into staging.
          git merge --allow-unrelated-histories dev

          #Push to staging Branch
          git push origin staging

  push_staging_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify your desired Python version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start and stop Python script
        run: |
          python main.py &               # Start the Python script in the background
          sleep 5s                      # Wait for 5 seconds (adjust the duration as needed)
          pkill -f "python main.py"      # Stop the Python script

      - name: Run Tests
        run: | 
          python test.py
        
      - name: Push staging to main
        run: |
          # Configure Git
          git config user.email "artitambe2602@gmail.com"
          git config user.name "Arti Tambe"

          #Fetch Remote Branches test branches
          git fetch origin 

          #Checkout main Branch
          git checkout main

          # Merge staging into main.
          git merge --allow-unrelated-histories staging

          #Push to main Branch
          git push origin main
